version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:129.0
    container_name: selenium
    ports:
      - 4444:4444  # Selenium サーバー
      - 7900:7900  # VNC（Seleniumの挙動を確認するためのGUI）
    shm_size: '2gb'
  
  python:
    build: .
    container_name: python-app
    depends_on:
      - selenium
    volumes:
      - .:/src
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    tty: true
