class IchikawaURL:
  booklist = 'https://www.library.city.ichikawa.lg.jp/winj/opac/'
  entrance = 'https://www.library.city.ichikawa.lg.jp/winj/opac/top.do'
  loginpage = 'https://www.library.city.ichikawa.lg.jp/winj/opac/login.do'
  toppage = 'https://www.library.city.ichikawa.lg.jp/winj/opac/login.do'
  search = 'https://www.library.city.ichikawa.lg.jp/winj/opac/search-detail.do'
  reserve = 'https://www.library.city.ichikawa.lg.jp/winj/opac/search-list.do'
  lend_list = 'https://www.library.city.ichikawa.lg.jp/winj/opac/lend-list.do'
  reserve_list = 'https://www.library.city.ichikawa.lg.jp/winj/opac/reserve-list.do'
  basket = 'https://www.library.city.ichikawa.lg.jp/winj/opac/reserve-basket.do'
  basket_delete = 'https://www.library.city.ichikawa.lg.jp/winj/opac/reserve-basket-delete.do'
  confirm = 'https://www.library.city.ichikawa.lg.jp/winj/opac/reserve-confirm.do'
  logout = 'https://www.library.city.ichikawa.lg.jp/winj/opac/logout.do'
  extend = 'https://www.library.city.ichikawa.lg.jp/winj/opac/lend-extension-confirm.do'
