name: Run python script

on:
  schedule:
    - cron: "01 22 * * *"
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker environment
        run: |
          docker compose  up -d --build

      - name: Run main script
        run: |
          docker exec python-app poetry run python3 library_reservation/main.py \
            --line_token "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
            --line_group_id "${{ secrets.LINE_GROUP_ID_PERSONAL }}" \
            --user_id "${{ secrets.LIBRARY_USER_ID }}" \
            --user_password "${{ secrets.LIBRARY_USER_PASSWORD }}"
